test release artifacts

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -75,6 +75,69 @@ jobs:
         path: |
          ./build/Untwine*
 
+  test:
+    name: Test ${{ github.ref_name }} release
+    runs-on: ubuntu-latest
+    needs: build
+    permissions:
+      contents: write
+    steps:
+     - uses: actions/download-artifact@v4
+       name: Download release artifact
+       with:
+         name: source-package-ubuntu-latest
+         path: release
+
+     - name: Verify checksums
+       shell: bash -l {0}
+       working-directory: ./release
+       run: |
+          set -e
+          sha256sum -c *.sha256sum
+
+
+     - name: Unzip
+       shell: bash -l {0}
+       working-directory: ./release
+       run: |
+          set -e
+          echo "Tagged version is $GITHUB_REF_NAME, checking that Untwine version is the same"
+          ls *
+          tar xvf Untwine-${{ github.ref_name }}-src.tar.bz2
+          cd Untwine-$GITHUB_REF_NAME-src
+
+     - uses: mamba-org/setup-micromamba@v2
+       name: Install mamba
+       with:
+         init-shell: bash
+         environment-file: "./release/Untwine-${{ github.ref_name }}-src/ci/environment.yml"
+         environment-name: "untwine"
+         cache-environment: true
+         cache-downloads: true
+
+     - name: Confirm release
+       shell: bash -l {0}
+       working-directory: ./release/Untwine-${{ github.ref_name }}-src
+       run: |
+          set -e
+          mkdir build
+          cd build
+
+          cmake   -G "Ninja"  \
+                -DCMAKE_BUILD_TYPE=Debug \
+                -DBUILD_TESTING=OFF \
+                -DCMAKE_INSTALL_PREFIX=${CONDA_PREFIX} \
+                ..
+
+          ninja install
+          export UNTWINE_VERSION=$(untwine --version | sed 's/.*(\(.*\))/\1/)
+          if [ $GITHUB_REF_NAME == $UNTWINE_VERSION ]; then
+            echo "Tagged version equals tree version. All good."
+          else
+            echo "Tagged version is $GITHUB_REF_NAME and Untwine version is $Untwine_VERSION. Failing"
+            exit 1;
+          fi
+
   release:
     name: Gather and attach release
     runs-on: ubuntu-latest
